# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='post_date_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_updated',
            new_name='post_date_updated',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='post_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
