# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20170617_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date_updated',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date_created',
            field=models.DateTimeField(),
        ),
    ]
