# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20170623_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
