# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20170623_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_text',
            field=models.CharField(max_length=30, verbose_name='Tag text'),
        ),
    ]
