# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20170625_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
