# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
